### ISSUE TITLE
need send option 

### ISSUE THREAD

**Issue by venu942000** [haniibrahim/SerialLogger#9]
hi 

i  like your seriallogger but can you add send option .

**Comment by haniibrahim** [comment]
Thank you. But SerialLogger was developed and is still a cross-platform serial data logger. No more no less. I never intended to extent it to a full terminal program by adding send capabilities. There are a lot terminal programs available, free, open source and commercial ones which contain this function.

If you want to have this function in SerialLogger, it is open source and under a free license. You can add this function yourself or find someone who do it for you. That is open source all about.
